version: "3.8"
volumes:
  postgis_data:

services:
  postgres:
    image: "postgres:latest"
    deploy:
#      replicas: 2
      placement:
        constraints:
          - "node.hostname==worker1"
#          - "node.role==worker"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: target
      POSTGRES_PASSWORD: target
    volumes:
      - postgis_data:/var/lib/postgresql/data/
    networks:
      - net-pgadmin
      - net-nginx
  
  pgadmin:
    image: "dpage/pgadmin4:6.21"
    deploy:
#      replicas: 3
      placement:
        constraints:
          - "node.hostname==worker1"
#          - "node.hostname!=manager1"
#          - "node.hostname!=manager2"
    environment:
      - PGADMIN_DEFAULT_EMAIL: felipe.araujo@targetso.com
      - PGADMIN_DEFAULT_PASSWORD: Target2024
#      - PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT: False
    ports:
      - "8080:80"
    networks:
      - net-pgadmin
      - traefik-pg
    depends_on:
      - postgres

  nginx:
    image: "nginx:latest"
    deploy:
      replicas: 2
      placement:
        constraints:
          - "node.role==manager"
    ports:
      - "8081:80"
    networks:
      - net-nginx
      - traefik-nginx
    depends_on:
      - postgres

  traefik:
    image: "traefik:latest"
    deploy:
      replicas: 3
      placement:
        constraints:
          - "node.role==manager"
    ports:
      - "8082:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - traefik-nginx
      - traefik-pg

networks:
  net-pgadmin:
    driver: overlay
  net-nginx:
    driver: overlay
  traefik-nginx:
    driver: overlay
  traefik-pg:
    driver: overlay
